{
  "swagger": "2.0",
  "info": {
    "version": "3.0.0",
    "title": "Parcel Logistics Service",
    "contact": {
      "name": "DI(FH) Maximilian Knor",
      "url": "http://blog.knor.net/"
    }
  },
  "basePath": "/api",
  "responses": {
    "400": {
      "description": "The operation failed due to an error.",
      "schema": {
        "$ref": "#/definitions/error"
      }
    },
    "parcelTrackingId": {
      "description": "Successfully submitted the new parcel",
      "schema": {
        "$ref": "#/definitions/newParcelInfo"
      }
    }
  },
  "paths": {
    "/parcel": {
      "post": {
        "operationId": "submitParcel",
        "x-ms-summary": "Submit new parcel",
        "summary": "Submit a new parcel to the logistics service.\n",
        "parameters": [{
          "name": "newParcel",
          "x-ms-summary": "New parcel to submit",
          "in": "body",
          "required": true,
          "schema": {
            "$ref": "#/definitions/parcel"
          }
        }],
        "responses": {
          "200": {
            "$ref": "#/responses/parcelTrackingId"
          },
          "400": {
            "$ref": "#/responses/400"
          }
        },
        "tags": [
          "parcel"
        ]
      }
    },
    "/parcel/{trackingId}": {
      "get": {
        "operationId": "trackParcel",
        "summary": "Find the latest tracking state of a parcel by its tracking ID.\n",
        "x-ms-summary": "Track a parcel",
        "parameters": [{
          "name": "trackingId",
          "in": "path",
          "required": true,
          "type": "string",
          "pattern": "^[A-Z0-9]{9}$",
          "description": "The tracking ID of the parcel.\nE.g. PYJRB4HZ6\n",
          "x-ms-summary": "Tracking ID"
        }],
        "responses": {
          "200": {
            "description": "Parcel exists, here's the tracking information.",
            "schema": {
              "$ref": "#/definitions/trackingInformation"
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "description": "Parcel does not exist with this tracking ID."
          }
        },
        "tags": [
          "parcel"
        ]
      }
    },
    "/parcel/{trackingId}/reportHop/{code}": {
      "post": {
        "operationId": "reportParcelHop",
        "x-ms-summary": "Report Parcel arrival at Hop",
        "summary": "Report that a Parcel has arrived at a certain hop either Warehouse or Truck.\n",
        "parameters": [{
            "name": "trackingId",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "^[A-Z0-9]{9}$",
            "description": "The tracking ID of the parcel.\nE.g. PYJRB4HZ6\n",
            "x-ms-summary": "Tracking ID"
          },
          {
            "name": "code",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "^[A-Z]{3}((\\-T\\d{5})|(\\d{2}))$",
            "description": "The Code of the hop (Warehouse or Truck).",
            "x-ms-summary": "Code of the hop"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully reported hop."
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "description": "Parcel does not exist with this tracking ID or hop with code not found.\n"
          }
        },
        "tags": [
          "parcel"
        ]
      }
    },
    "/parcel/{trackingId}/reportDelivery/": {
      "post": {
        "operationId": "reportParcelDelivery",
        "x-ms-summary": "Report Parcel delivery at final destination",
        "summary": "Report that a Parcel has been delivered at it's final destination address.\n",
        "parameters": [{
          "name": "trackingId",
          "in": "path",
          "required": true,
          "type": "string",
          "pattern": "^[A-Z0-9]{9}$",
          "description": "The tracking ID of the parcel.\nE.g. PYJRB4HZ6\n",
          "x-ms-summary": "Tracking ID"
        }],
        "responses": {
          "200": {
            "description": "Successfully reported hop."
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "description": "Parcel does not exist with this tracking ID.\n"
          }
        },
        "tags": [
          "parcel"
        ]
      }
    },
    "/warehouse": {
      "post": {
        "operationId": "importWarehouses",
        "x-ms-summary": "Import Warehouses",
        "summary": "Imports a hierarchy of Warehouse and Truck objects.\n",
        "parameters": [{
          "name": "rootWarehouse",
          "in": "body",
          "required": true,
          "x-ms-summary": "Root Warehouse",
          "schema": {
            "$ref": "#/definitions/warehouse"
          }
        }],
        "responses": {
          "200": {
            "description": "Successfully loaded."
          },
          "400": {
            "$ref": "#/responses/400"
          }
        },
        "tags": [
          "warehouse"
        ]
      },
      "get": {
        "operationId": "exportWarehouses",
        "x-ms-summary": "Export warehouse hierarchy.",
        "summary": "Exports the hierarchy of Warehouse and Truck objects.\n",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/warehouse"
            }
          },
          "400": {
            "description": "An error occurred loading.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "404": {
            "description": "No hierarchy loaded yet."
          }
        },
        "tags": [
          "warehouse"
        ]
      }
    }
  },
  "produces": [
    "application/json"
  ],
  "consumes": [
    "application/json"
  ],
  "definitions": {
    "parcel": {
      "type": "object",
      "properties": {
        "weight": {
          "type": "number",
          "format": "float"
        },
        "receipient": {
          "$ref": "#/definitions/receipient"
        }
      },
      "required": [
        "weight",
        "receipient"
      ],
      "example": {
        "weight": 5.2,
        "receipient": {
          "firstName": "Tux L.-Oves",
          "lastName": "Azure",
          "street": "Am Europlatz 3",
          "postalCode": "A-1120",
          "city": "Wien"
        }
      }
    },
    "receipient": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "street": {
          "type": "string"
        },
        "postalCode": {
          "type": "string"
        },
        "city": {
          "type": "string"
        }
      },
      "required": [
        "firstName",
        "lastName",
        "street",
        "postalCode",
        "city"
      ],
      "example": {
        "firstName": "Tux L.-Oves",
        "lastName": "Azure",
        "street": "Am Europlatz 3",
        "postalCode": "A-1120",
        "city": "Wien"
      }
    },
    "warehouse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "pattern": "^[A-Z]{3}\\d{1,2}$"
        },
        "description": {
          "type": "string"
        },
        "duration": {
          "type": "number"
        },
        "nextHops": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/warehouse"
          }
        },
        "trucks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/truck"
          }
        }
      },
      "required": [
        "code",
        "description",
        "duration"
      ],
      "example": {
        "code": "FRA01",
        "description": "Main Warehouse Germany",
        "duration": 10,
        "nextHops": [{
          "code": "FRA02",
          "description": "Regional Warehouse Frankfurt",
          "duration": 5,
          "nextHops": [{
            "code": "BER01",
            "description": "Warehouse Berlin",
            "duration": 22,
            "nextHops": [{
              "code": "VIE01",
              "description": "Warehouse Wien",
              "duration": 25,
              "nextHops": [],
              "trucks": [{
                "code": "VIE-T12345",
                "numberPlate": "W-123123",
                "latitude": 12,
                "longitude": 12,
                "radius": 12,
                "duration": 5
              }]
            }],
            "trucks": [{
                "code": "BER-T12345",
                "numberPlate": "M-123123",
                "latitude": 12,
                "longitude": 12,
                "radius": 12,
                "duration": 5
              },
              {
                "code": "BER-T11111",
                "numberPlate": "M-456456",
                "latitude": 13,
                "longitude": 13,
                "radius": 5,
                "duration": 10
              }
            ]
          }],
          "trucks": []
        }],
        "trucks": []
      }
    },
    "error": {
      "properties": {
        "errorMessage": {
          "type": "string",
          "description": "The error message."
        }
      },
      "required": [
        "errorMessage"
      ]
    },
    "newParcelInfo": {
      "properties": {
        "trackingId": {
          "type": "string",
          "pattern": "^[A-Z0-9]{9}$",
          "description": "The tracking ID of the parcel.\n",
          "example": "PYJRB4HZ6"
        }
      }
    },
    "truck": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "pattern": "^[A-Z]{3}\\-T\\d{5}$"
        },
        "numberPlate": {
          "type": "string"
        },
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        },
        "radius": {
          "type": "number"
        },
        "duration": {
          "type": "number"
        }
      },
      "required": [
        "code",
        "numberPlate",
        "latitude",
        "longitude",
        "radius",
        "duration"
      ]
    },
    "hopArrival": {
      "type": "object",
      "required": [
        "code",
        "dateTime"
      ],
      "properties": {
        "code": {
          "type": "string",
          "description": "The code of the warehouse or truck.",
          "pattern": "^[A-Z]{3}((\\-T\\d{5})|(\\d{2}))$"
        },
        "dateTime": {
          "description": "The date/time the parcel arrived at the hop.",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "trackingInformation": {
      "type": "object",
      "example": {
        "state": "InTransport",
        "visitedHops": [{
            "code": "VIE01",
            "dateTime": "2016-10-25T07:44:00.00Z"
          },
          {
            "code": "FRA02",
            "dateTime": "2016-10-25T09:20:00.00Z"
          }
        ],
        "futureHops": [{
            "code": "BER01",
            "dateTime": "2016-10-25T16:00:00.00Z"
          },
          {
            "code": "BER-T12345",
            "dateTime": "2016-10-25T18:00:00.00Z"
          }
        ]
      },
      "required": [
        "state",
        "visitedHops",
        "futureHops"
      ],
      "properties": {
        "state": {
          "type": "string",
          "description": "State of the parcel.",
          "enum": [
            "InTransport",
            "InTruckDelivery",
            "Delivered"
          ]
        },
        "visitedHops": {
          "type": "array",
          "description": "Hops visited in the past - either warehouse or truck.",
          "items": {
            "$ref": "#/definitions/hopArrival"
          }
        },
        "futureHops": {
          "type": "array",
          "description": "Hops coming up in the future - their times are estimations.",
          "items": {
            "$ref": "#/definitions/hopArrival"
          }
        }
      }
    }
  }
}